<?php

declare(strict_types=1);

namespace App\DataFixtures;

use App\Factory\CategoryFactory;
use Doctrine\Bundle\FixturesBundle\Fixture;
use Doctrine\Persistence\ObjectManager;

class CategoryFixtures extends Fixture
{
    public function __construct(
        private readonly CategoryFactory $categoryFactory
    ) {
    }

    public function load(ObjectManager $manager): void
    {
        foreach ($this->getAllCategories() as $title) {
            $category = $this->categoryFactory->create(title: $title);
            $manager->persist($category);
        }
        $manager->flush();
    }

    /**
     * @return array<string>
     */
    public function getAllCategories(): array
    {
        return [
            'category.live-performance',
            'category.music-concert',
            'category.theater-show',
            'category.dance-show',
            'category.comedy-show',
            'category.magic-show',
            'category.comedy',
            'category.circus',
            'category.celebration',
            'category.birthday-party',
            'category.anniversary',
            'category.wedding',
            'category.educational',
            'category.educational.presentation',
            'category.educational.coding-bootcamp',
            'category.educational.workshop',
            'category.educational.lecture',
            'category.educational.seminar',
            'category.educational.conference',
            'category.educational.training_session',
            'category.educational.academic_talk',
            'category.exhibition',
            'category.exhibition.art_show',
            'category.exhibition.science_expo',
            'category.exhibition.trade_fair',
            'category.exhibition.fashion_show',
            'category.exhibition.auto_exhibition',
            'category.exhibition.virtual_experience',
            'category.festival',
            'category.festival.music_festival',
            'category.festival.food_and_drink_festival',
            'category.festival.cultural_festival',
            'category.festival.film_festival',
            'category.festival.literary_festival',
            'category.festival.seasonal_celebration',
            'category.food_and_drink',
            'category.food_and_drink.food_tasting',
            'category.food_and_drink.wine_tasting_event',
            'category.food_and_drink.beer_festival',
            'category.food_and_drink.culinary_workshop',
            'category.food_and_drink.restaurant_opening',
            'category.food_and_drink.cooking_class',
            'category.social_issues.labor_protest',
            'category.social_issues.labor_strike',
            'category.social_issues.worker_protest',
            'category.social_issues.union_meeting',
            'category.fundraising',
            'category.fundraising.charity_auction',
            'category.fundraising.walkathon',
            'category.fundraising.crowdfunding_campaign',
            'category.fundraising.gala_event',
            'category.fundraising.charity_run',
            'category.fundraising.volunteer_drive',
            'category.gaming',
            'category.gaming.video_game_tournament',
            'category.gaming.board_game_night',
            'category.gaming.role_playing_game_session',
            'category.gaming.esports_event',
            'category.gaming.game_development_meetup',
            'category.health_and_wellness',
            'category.health_and_wellness.wellness-coaching',
            'category.health_and_wellness.yoga_session',
            'category.health_and_wellness.holistic-health-retreat',
            'category.health_and_wellness.mindfulness_workshop',
            'category.health_and_wellness.fitness_class',
            'category.health_and_wellness.nutrition_seminar',
            'category.health_and_wellness.meditation_event',
            'category.health_and_wellness.wellness_retreat',
            'category.hobby',
            'category.painting',
            'category.drawing',
            'category.photography',
            'category.crafting',
            'category.gardening',
            'category.model_building',
            'category.hobby.model_building',
            'category.hobby.diy',
            'category.holiday',
            'category.holiday.christmas_celebration',
            'category.holiday.new_years_eve_party',
            'category.holiday.thanksgiving_event',
            'category.holiday.halloween_party',
            'category.holiday.independence_day_celebration',
            'category.holiday.valentines_day_special',
            'category.holiday.national-holiday',
            'category.business_networking',
            'category.business.networking_event',
            'category.business.seminar',
            'category.business.product_launch',
            'category.business.career_fair',
            'category.business.startup_showcase',
            'category.outdoor',
            'category.outdoor.biking',
            'category.outdoor.bird-watching',
            'category.outdoor.camping',
            'category.outdoor.stargazing',
            'category.outdoor.cycling',
            'category.outdoor.running',
            'category.outdoor.fishing',
            'category.outdoor.picnic',
            'category.party',
            'category.party.birthday',
            'category.party.themed-party',
            'category.party.bbq',
            'category.party.outdoor',
            'category.party.dinner',
            'category.party.bar-hopping',
            'category.party.birthday_party',
            'category.party.graduation_celebration',
            'category.party.retirement_party',
            'category.party.theme_party',
            'category.party.costume_party',
            'category.party.house_party',
            'category.arts_and_culture.writing_and_literature',
            'category.writing_and_literature.creative_writing_workshop',
            'category.writing_and_literature.book_club_meeting',
            'category.writing_and_literature.author_meet_and_greet',
            'category.writing_and_literature.poetry_slam',
            'category.screenwriting',
            'category.social',
            'category.social.after-work-drink',
            'category.social.movie_night',
            'category.social.mixer',
            'category.social.meet_and_greet_event',
            'category.social.friendship_event',
            'category.social.community_gathering',
            'category.social.networking_party',
            'category.social.speed_dating',
            'category.sports',
            'category.team_sport',
            'category.individual_sport',
            'category.running_event',
            'category.cycling_tournament',
            'category.water_sports_competition',
            'category.sports.extreme_sport',
            'category.competition-sport',
            'category.technology',
            'category.technology.co-coding',
            'category.technology.tech_conference',
            'category.technology.hackathon',
            'category.technology.gaming_event',
            'category.technology.startup_meetup',
            'category.technology.coding_workshop',
            'category.technology.innovation_forum',
            'category.technology.tech-fair',
            'category.technology.demonstration',
            'category.travel',
            'category.travel.adventure_tour',
            'category.travel.beach_vacation',
            'category.travel.city_exploration',
            'category.travel.road-trip',
            'category.travel.car-pool',
            'category.travel.cruise',
            'category.travel.hiking_excursion',
            'category.travel.wildlife_safari',
            'category.workshop',
            'category.workshop.pottery',
            'category.workshop.painting',
            'category.workshop.sculpture',
            'category.workshop.ceramics',
            'category.workshop.skill_building',
            'category.workshop.crafting_workshop',
            'category.workshop.tech_workshop',
            'category.workshop.business_workshop',
            'category.workshop',
            'category.workshop.personal_development',
            'category.workshop.language_learning',
            'category.workshop.gardening',
            'category.workshop.sustainable-living',
        ];
    }
}
