version: "3.9"

networks:
  traefik:
    external: true
  internal:
    external: false

volumes:
  php_socket:
  caddy_data:
  caddy_config:

services:
  php:
    image: ghcr.io/eventpoints/eventpoint.app-php:main
    volumes:
      - php_socket:/var/run/php
      - ./php/php.ini:/usr/local/etc/php/php.ini
    healthcheck:
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 30s
    depends_on:
      - database
    restart: unless-stopped
    environment:
      MERCURE_PUBLIC_URL: "https://eventpoint.app/.well-known/mercure"
      APP_ENV: "prod"
      DATABASE_URL: "postgresql://${{ secrets.EVENTPOINT_POSTGRES_USER }}:${{ secrets.EVENTPOINT_POSTGRES_PASSWORD }}@database:5432/${{ secrets.EVENTPOINT_POSTGRES_DBNAME }}?serverVersion=13&charset=utf8"
      MERCURE_JWT_SECRET: "${{ secrets.EVENTPOINT_MERCURE_JWT_SECRET }}"
      APP_SECRET: "${{ secrets.EVENTPOINT_APP_SECRET }}"
      MAILER_DSN: "${{ secrets.EVENTPOINT_MAILER_DSN }}"
      OAUTH_FACEBOOK_ID: "${{ secrets.EVENTPOINT_OAUTH_FACEBOOK_ID }}"
      OAUTH_FACEBOOK_SECRET: "${{ secrets.EVENTPOINT_OAUTH_FACEBOOK_SECRET }}"
      OAUTH_GOOGLE_ID: "${{ secrets.EVENTPOINT_OAUTH_GOOGLE_ID }}"
      OAUTH_GOOGLE_SECRET: "${{ secrets.EVENTPOINT_OAUTH_GOOGLE_SECRET }}"
      MAPBOX_TOKEN: "${{ secrets.EVENTPOINT_MAPBOX_TOKEN }}"
      MESSENGER_TRANSPORT_DSN: "${{ secrets.EVENTPOINT_MESSENGER_TRANSPORT_DSN }}"
      SUPPORTED_LOCALES: "${{ secrets.EVENTPOINT_SUPPORTED_LOCALES }}"
      APP_TIMEZONE: "${{ secrets.EVENTPOINT_APP_TIMEZONE }}"
      CORS_ALLOW_ORIGIN: "${{ secrets.EVENTPOINT_CORS_ALLOW_ORIGIN }}"
      CLOUDFLARE_TURNSTILE_PUBLIC_KEY: "${{ secrets.EVENTPOINT_CLOUDFLARE_TURNSTILE_PUBLIC_KEY }}"
      CLOUDFLARE_TURNSTILE_PRIVATE_KEY: "${{ secrets.EVENTPOINT_CLOUDFLARE_TURNSTILE_PRIVATE_KEY }}"
    networks:
      - internal

  caddy:
    image: ghcr.io/eventpoints/eventpoint.app-caddy:main
    depends_on:
      - php
    restart: unless-stopped
    environment:
      SERVER_NAME: ":80"
      MERCURE_PUBLISHER_JWT_KEY: "${{ secrets.__EVENTPOINT_MERCURE_JWT_SECRET__ }}"
      MERCURE_SUBSCRIBER_JWT_KEY: "${{ secrets.__EVENTPOINT_MERCURE_JWT_SECRET__ }}"
    volumes:
      - php_socket:/var/run/php
      - caddy_data:/data
      - caddy_config:/config
      - ./Caddyfile:/etc/caddy/Caddyfile
    expose:
      - "80"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.eventpoint.rule=Host(`eventpoint.app`, `www.eventpoint.app`)"
      - "traefik.http.routers.eventpoint.tls=true"
      - "traefik.http.routers.eventpoint.tls.certresolver=le"
    networks:
      - traefik
      - internal

  database:
    image: postgres:13
    restart: unless-stopped
    environment:
      POSTGRES_DB: "__EVENTPOINT_POSTGRES_DBNAME__"
      POSTGRES_PASSWORD: "__EVENTPOINT_POSTGRES_PASSWORD__"
      POSTGRES_USER: "__EVENTPOINT_POSTGRES_USER__"
    volumes:
      - ./db-data:/var/lib/postgresql/data:rw
    networks:
      - internal

  adminer:
    image: adminer:4.8.0
    restart: unless-stopped
    environment:
      ADMINER_DEFAULT_SERVER: database
    expose:
      - "8080"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.eventpoint-adminer.rule=Host(`adminer.eventpoint.app`)"
      - "traefik.http.routers.eventpoint-adminer.tls=true"
      - "traefik.http.routers.eventpoint-adminer.tls.certresolver=le"
    networks:
      - internal
      - traefik
